### ISSUE TITLE
StoryMap13 NLK: Please change a word in DE Infobox

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/web-storymap12#64]
Liebe Daniela

Vielen Dank für die Arbeit und das gelungene Resultat!
Wir werden die Story-Map natürlich noch auf den NLK Seiten integrieren.

Mir ist grad nur noch ein kleiner Fehler aufgefallen

Es sollte Karten
![Uploading AW  Vorinformation - Neue StoryMap  Neue Landeskarten für die Schweiz   am 16 09 2014.msg . . .]()
 im Geoportal des Bundes heissen.

Lieber Gruss und schönes Weekend mit hoffentlich ein paar Sonnenstrahlen 

Andrea

**Comment by procrastinatio** [comment]
No more storymaps
